name: Pull Request Workflow

on:
  workflow_dispatch:

jobs:
  terraform-checks:
    uses: baezag/iac-components/.github/workflows/test.yaml@dev
    with:
      environment: ${{ github.ref_name }}
      workspace: ${GITHUB_REPOSITORY#*/}
    secrets: inherit
    